### ISSUE TITLE
Display name of the current user seems to get lost, when you leave a room.

### ISSUE THREAD

**Issue by maralorn** [QMatrixClient/Quaternion#105]

**Comment by KitsuneRal** [comment]
This is a consequence of a larger problem - only the most recent room state is currently remembered. Another manifestation of this problem is that any renaming event will cause renaming in the whole timeline (the QML cache mitigates that but only to an extent).

**Comment by maralorn** [comment]
Yeah, I know about the larger problem. The weird thing is: When I leave in one room after that my display name won’t be shown in any room. This is a further bug in my opinion.

**Comment by KitsuneRal** [comment]
Woah, didn't notice that. Surely a bug on its own.

**Comment by KitsuneRal** [comment]
Are you listed among members in other rooms _in Quaternion_ after leaving?

**Comment by maralorn** [comment]
Jop, but only with the mxid
