### ISSUE TITLE
Save scroll state per room

### ISSUE THREAD

**Issue by maralorn** [QMatrixClient/Quaternion#111]
And perhaps scroll room to readmarker on open

**Comment by KitsuneRal** [comment]
Yes to saving the scroll state; but scrolling to _readmarker_ is another thing and it's questionable. They say that Slack does it (I'm not using Slack so can't say anything), and that scrolling to the last read place is controversial. From my experience, I'd make it at least optional, and I'm not sure if its even valuable compared to "last remembered position or just the very latest if I've been at the very latest".

**Comment by Qwertie-** [comment]
I have seen a few IM clients that do this. Telegram for example will open a room from where you last left it and have a down arrow at the bottom to return to the latest messages.

**Comment by grahamperrin** [comment]
> Save scroll state per room

👍 as a user preference. 

> … scroll room to readmarker on open

I might prefer that _occasionally_ … gut feeling, I'd more often prefer a saved scroll state.
