### ISSUE TITLE
Make timeline scrollable with keys

### ISSUE THREAD

**Issue by maralorn** [QMatrixClient/Quaternion#123]

**Comment by miocho** [comment]
here, with v0.0.9.3 on linux, scrolling with keyboard works partially. using up/down arrow keys, it seems for a moment as if it gets stuck, esp. when changing scrolling direction, although it is just very slow to react initially and works okay if i leave the button pressed for longer.

scrolling with page-up/page-down buttons does not work at all.

**Comment by KitsuneRal** [comment]
3f9aeafa7199f93d0b877df45d99bb09130ce286 brings ability to scroll the timeline with Ctrl-PageUp/Down, and (if the timeline, rather than message input box is focused), with Up and Down keys. Feedback is welcome.

**Comment by ptman** [comment]
excellent! but why is ctrl needed?

**Comment by KitsuneRal** [comment]
Because for now PageUp/Down are consumed by the message entry box itself (since it's multiline). Further on I'm going to use plain PageUp/Down to scroll around and maaaybe Ctrl-PageUp/Down to page through long messages (but I don't want to facilitate long messages so might as well just drop it).
