### ISSUE TITLE
fails to login on Windows with "Error creating SSL context"

### ISSUE THREAD

**Issue by okurz** [QMatrixClient/Quaternion#126]
## observation

starting Quaternion 0.0.65/0.0.1 on Windows and trying to connect to https://matrix.org fails with error message "Error creating SSL context"

## steps to reproduce

What works for me:
* extract Windows zip file
* start
* connect with parameters as mentioned above
* observe error

## expected result

should connect to server.

**Comment by KitsuneRal** [comment]
Do you have libssl/ssleay libraries reachable, as described [here](https://github.com/Fxrh/Quaternion#installation-on-windows)?

**Comment by okurz** [comment]
no, sorry. I did not read this documentation part regarding Windows installation. It might make sense to add a check to the code (for win32/64 only) to check if the dll could be loaded. Anyway, I will try the installation procedure as described later on. If you prefer you can also close the issue right now. Thank you.

**Comment by KitsuneRal** [comment]
You've got the point; I'll see what kind of checks for SSL sanity can be added. Having said that, Quaternion is not yet really good at checking any kind of error conditions (not only SSL-related)...

**Comment by okurz** [comment]
I managed to download 32bit as well as 64bit variants of the two dlls in questions from some shady webpages and put them next to quaternion.exe but to no avail. Showed same symptoms. Windows is complicated compared to GNU/Linux ;-)

**Comment by KitsuneRal** [comment]
I'm afraid you have to go through some dancing with depends.exe (as mentioned in the same place) to find out if the dll's actually get loaded properly. And yes, the whole dll thing is quite precarious on Windows.

**Comment by KitsuneRal** [comment]
Okay, seems it bit me as well, as of yesterday.

**Comment by KitsuneRal** [comment]
I have slightly updated README.md (https://github.com/QMatrixClient/Quaternion/commit/1cc1d4adba97551dbdc32e753e00bdbf13e25816) to better describe that topic.

**Comment by mcarifio** [comment]
Unfortunately this still doesn't work with Version 0.0.9.3 and https://slproweb.com/download/Win64OpenSSL-1_1_1a.exe. The openssl installation procedure puts *.dll in System32 but I still get the SSL error cited above.

**Comment by KitsuneRal** [comment]
Does [Dependency Walker](http://dependencywalker.com/) show anything suspicious? You may be trying to link a 32-bit executable with a 64-bit library, e.g.
