### ISSUE TITLE
window disappears after suspend/resume

### ISSUE THREAD

**Issue by uhoreg** [QMatrixClient/Quaternion#165]
The Quaternion window seems to completely disappear after a suspend and resume, and there doesn't seem to be any way of getting it back.  The process is still running, but the window is gone.  This is on Linux.

**Comment by KitsuneRal** [comment]
If the window is entirely out (including the frame), this looks like a window manager glitch - possibly exacerbated by some issue with Qt and/or Quaternion. Let's try to do some differential diagnosis first. Do you have other Qt applications and if yes, do they behave the same way? If not, (just in case), are they built with the same version of Qt? More information about the environment would also help - distribution, desktop environment. If you can try a different desktop environment that would also help.

**Comment by uhoreg** [comment]
Window manager is xmonad + XFCE.  I don't run any other Qt programs.  I'll try to find another Qt program to run.

**Comment by elvisangelaccio** [comment]
Version of Qt? This could be https://bugreports.qt.io/browse/QTBUG-61140

**Comment by uhoreg** [comment]
Qt 5.3.2, so probably not that bug

**Comment by KitsuneRal** [comment]
Please find another Qt application and try it. We at least need to make sure the problem is between Qt and the window manager and not in the way Quaternion uses Qt.

**Comment by uhoreg** [comment]
Same thing happens with another Qt application, so it's obviously not a Quaternion issue.  Closing.
