### ISSUE TITLE
No chat window with dark theme

### ISSUE THREAD

**Issue by Midek** [QMatrixClient/Quaternion#170]
With default qt theme everything seems to be fine, but after setting my theme to breeze-dark, main chat window seems to be invisible.
[screen]: http://midov.pl/share/2017-08-17-140123_1275x1416_scrot.png

**Comment by Midek** [comment]
This might actually be fault of the theme itself since on couple other dark themes i tried it does seem to work (like qtCurve)
Weird that it does not work with breeze though, since its default theme for KDE.

**Comment by KitsuneRal** [comment]
@Midek, just in case - after switching to the dark-theme, did you try to switch back to default (or whatever else)? If yes, was the chat widget showing properly? The screenshot looks as if the whole thing just ceased working; if that's the case, it should stay so after switching back. I just would like to rule out a case that a problem is somewhere in QML engine or Quaternion.

**Comment by Midek** [comment]
Hey, @KitsuneRal .
No, after switching to normal white theme Quaternion was working as intended, and after swithing back to breeze chat window dissapeared again.

I am not running any DE, so im setting my theme with qt5ct after setting `export QT_QPA_PLATFORMTHEME="qt5ct"` in `/etc/profile` if that helps.

**Comment by KitsuneRal** [comment]
Ah, qt5ct. That may actually produce its own set of issues, even though it seems to be the only standalone way of switching Qt themes on Linux. I wouldn't be surprised to find out that the same case works flawlessly under KDE. Can't help with this, I'm afraid; but thanks for reporting it, anyway.
