### ISSUE TITLE
linkify URLs that are enclosed in angle brackets < >

### ISSUE THREAD

**Issue by grahamperrin** [QMatrixClient/Quaternion#171]
![2017-08-21 03 31 11 qmatrixclient quaternion lib quaternion](https://user-images.githubusercontent.com/192271/29501569-66fa1080-8621-11e7-9c9d-f773b0b2e523.png)

<https://tools.ietf.org/html/rfc3986#appendix-C>

> `… In practice, URIs are delimited in a variety of ways, but usually within double-quotes "http://example.com/", angle brackets <http://example.com/>, or just by using whitespace: …`

**Comment by KitsuneRal** [comment]
Closed by #177
