### ISSUE TITLE
images in Quaternion

### ISSUE THREAD

**Issue by grahamperrin** [QMatrixClient/Quaternion#172]
The image at <https://matrix.to/#/!PCzUtxtOjUySxSelof:matrix.org/$15032811104659681PcDZs:matrix.org> is visible on Linux (to @uhoreg) but not on FreeBSD-CURRENT: 

![2017-08-21 03 31 11 qmatrixclient quaternion lib quaternion](https://user-images.githubusercontent.com/192271/29501569-66fa1080-8621-11e7-9c9d-f773b0b2e523.png)

[CMakeOutput.log.txt](https://github.com/QMatrixClient/Quaternion/files/1237644/CMakeOutput.log.txt)

**Comment by grahamperrin** [comment]
At the time of writing (Monday evening) the issue is no longer reproducible. 

To the best of my recollection: 

1. this morning at home I used the Displays pane of System Settings to disable an HP display that was on VGA, and to enable the built-in display (can't recall whether the built-in was previously disabled) 
2. removed the VGA cable
3. slept the notebook (HP EliteBook 8570p)
4. woke the notebook at work in a dock with a Philips display on one of the DisplayPort connectors of the dock
5. used the Displays pane to enable the Philips display and to disable the built-in display
6. this afternoon at work I slept the notebook 
7. removed the notebook from the Dock
8. at home I remade the VGA connection
9. used the Displays pane to enable the display on VGA, and to disable the built-in display
10. brought Quaternion to front and resized its window
11. _maybe_ a flicker before the images appeared …

**Comment by grahamperrin** [comment]
I might have made the bug reproducible with the `#quaternion:matrix.org` room: 

1. launch the application
2. select the room
3. observe the three recent images
4. use the infinite scroll button (or whatever it's called) to scroll to mid-May 2017
5. click the arrow to return to the most recent message.

Terminal output, beginning before the scroll up to mid-May: 

```text
Read marker is off-screen
Bottommost shown message index was 99
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
libqmatrixclient.events: Unknown msgtype: ""
ImageProvider::requestPixmap: "matrix.org/XMMfEmKIlYaVQPdexGCwajVk"
gotImage
ImageProvider::requestPixmap: "matrix.org/iaEWYUAWOxDqwjazGNdjKFyg"
libqmatrixclient.jobs: Job "MediaThumbnailJob" status 104 : "Error transferring https://matrix.org/_matrix/media/v1/thumbnail/matrix.org/iaEWYUAWOxDqwjazGNdjKFyg?width=500&height=500&method=scale&access_token=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDJiY2lkIHVzZXJfaWQgPSBAZ3JhaGFtcGVycmluOm1hdHJpeC5vcmcKMDAxNmNpZCB0eXBlID0gYWNjZXNzCjAwMjFjaWQgbm9uY2UgPSBfcEIwdDN4c0hfazNqNV5sCjAwMmZzaWduYXR1cmUgkMji9ECtYXNXilwtrMGSnYqZRiSsSL5AMoRRuBErntIK - server replied: Not Found"
Read marker is on-screen, at (99|"$15032862124703592FfjOn:matrix.org")
Read marker is off-screen
Bottommost shown message index was 99
Read marker is on-screen, at (99|"$15032862124703592FfjOn:matrix.org")
```

– does that output help?

**Comment by KitsuneRal** [comment]
Very sorry for taking so long. I could reproduce this on my side as well - kudos to you for the testcase. Now I at least have no excuse to figure what is going on with images...

**Comment by grahamperrin** [comment]
No need to apologise :-)

**Comment by KitsuneRal** [comment]
Now that images are cached locally and opened from a file - can you try to reproduce again? You need the very latest master branch of Quaternion (and of the library).

**Comment by KitsuneRal** [comment]
After trying to reproduce in various way I conclude that this is fixed now that the library caches images rather than the QML engine.

**Comment by grahamperrin** [comment]
Sorry, haven't found time to revisit this. I'll take a look … eventually. Thanks for the work!
