### ISSUE TITLE
control character u0003 (Unicode END OF TEXT; ETX) visible in some situations

### ISSUE THREAD

**Issue by grahamperrin** [QMatrixClient/Quaternion#173]
For example, from <https://matrix.to/#/!xAcrCyjpCWOtluwgSS:matrix.org/$1502904766199764znoaW:matrix.org>: 

```text
{
    "content": {
        "body": "[vertical-tabs-reloaded] Croydon commented on issue #13: [Meta] Refactor to WebExtension add-on - https://github.com/Croydon/vertical-tabs-reloaded/issues/13#issuecomment-322844011",
        "format": "org.matrix.custom.html",
        "formatted_body": "\u0003[<font color=\"navy\">vertical-tabs-reloaded</font>\u0003] <font color=\"olive\">Croydon</font>\u0003 commented on issue <font color=\"green\">#13</font>\u0003: [Meta] Refactor to WebExtension add-on - <font color=\"fuchsia\">https://github.com/Croydon/vertical-tabs-reloaded/issues/13#issuecomment-322844011</font>\u0003",
        "msgtype": "m.text"
    },
    "event_id": "$1502904766199764znoaW:matrix.org",
    "origin_server_ts": 1502904766806,
    "sender": "@freenode_Not-ff0b:matrix.org",
    "type": "m.room.message",
    "unsigned": {
        "age": 468471184
    }
}
```

Riot and Quaternion views of that point on the timeline: 

![image](https://user-images.githubusercontent.com/192271/29556607-3a1403e8-871e-11e7-9b13-0dbdac49a8c8.png)

![image](https://user-images.githubusercontent.com/192271/29556618-41830a2a-871e-11e7-950c-e7bcfd8b309f.png)

## Environment

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% uname -v
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% 
```

## Reference

[END OF TEXT; ETX at unicode.org](http://unicode.org/cldr/utility/list-unicodeset.jsp?a=[:Name_Alias%CE%B2=END%20OF%20TEXT;%20ETX:])

## Side note

The links are not linkified, which makes me wonder whether this is more than a cosmetic issue. (Aim to reproduce both issues with something other than FreeBSD.)

**Comment by KitsuneRal** [comment]
@grahamperrin, for the record, can you put the used Qt version here as well?

**Comment by KitsuneRal** [comment]
Aaand your locale might matter, so please mention it as well. Just in case.

**Comment by KitsuneRal** [comment]
A, wait. I just realized that you receive `\u0003` in `formatted_body`, and apparently, this stuff comes from some bot - so I'm afraid you should ask the bot writer why those control characters are in there at all. The font used by Quaternion is simply more diligent at displaying those, compared to whatever font your SeaMonkey uses for Riot. Stripping control characters out of the message is definitely not the way to go for us.
