### ISSUE TITLE
UI improvement: allow removing empty lines between messages

### ISSUE THREAD

**Issue by tidux** [QMatrixClient/Quaternion#178]
The default is probably more readable for new users, but zero lines between messages would give Quaternion equivalent lines-per-window to an IRC client using the same font.

**Comment by KitsuneRal** [comment]
As written in the commit message, you can use the option UI/condense_chat for that. Depending on the platform, you should look either in the Windows registry or in `~/.config`

**Comment by tidux** [comment]
Sweet, thanks!
