### ISSUE TITLE
Native scrollbars

### ISSUE THREAD

**Issue by dimqua** [QMatrixClient/Quaternion#187]
Please use native scrollbars for the chat history. Currently they look like this on my KDE Plasma 5 system:

![](https://i.imgur.com/8YWFeGS.png)

**Comment by KitsuneRal** [comment]
It's not really a scroll bar, at least not a classic one; I probably should make it less similar to a scroll bar. Try to drag it and see the difference.

**Comment by ptman** [comment]
It's a very small target to grab. I wouldn't mind if keyboard scrolling worked #123

**Comment by KitsuneRal** [comment]
This is available as an option now, as of 454f03004610723943539c32ac1a546cfc7a8884.
