### ISSUE TITLE
Add HTTP proxy support

### ISSUE THREAD

**Issue by krombel** [QMatrixClient/Quaternion#188]
just for reference for people searching for it. This will be implemented/tracked in QMatrixClient/libqmatrixclient#111

**Comment by KitsuneRal** [comment]
As noted in the QMatrixClient/libqmatrixclient#111, all functionality is already available from Qt, it only needs wiring in the UI.

**Comment by KitsuneRal** [comment]
@krombel, will HTTP proxy without authentication be enough or you have an authenticated proxy?
(I realise that eventually we'll have to support authenticated proxies too but that's a bigger piece of work, unless we force users to enter the proxy password at every Quaternion startup.)

**Comment by krombel** [comment]
I am behind an authenticating proxy...
But it would be OK for me to type the auth data in at every login (as the data changes from time to time)

**Comment by KitsuneRal** [comment]
As of now, authenticated proxies are only supported by using system defaults (the main switch is off in the network proxy settings dialog) and passing `HTTP_PROXY` and/or `HTTPS_PROXY` environment variable when starting Quaternion. An authentication dialog is on the way.
