### ISSUE TITLE
Linkifier is too greedy and includes `)`

### ISSUE THREAD

**Issue by t3chguy** [QMatrixClient/Quaternion#189]
Message of `
(https://view.matrix.org/room/!cURbafjkfsMDVwdRDQ:matrix.org/servers)` got linkified to include the trailing `)` thus breaking the link

**Comment by KitsuneRal** [comment]
It's only one the problems with the current linkifier. Another couple is described here: https://github.com/QMatrixClient/Quaternion/issues/183

**Comment by KitsuneRal** [comment]
The same happens to trailing quotes. However, the case of parenthesis seems ambiguous, as the parenthesis (as well as comma, colon and many others) are perfectly valid characters for a URI. Apparently there should be some exclusion for using URLs in a "colloquial speech", and I suppose it should be like this: any such ambiguous character, if it's not supposed to be a part of a URL, should be followed by a whitespace or end-of-line.
