### ISSUE TITLE
Sort rooms in the room list

### ISSUE THREAD

**Issue by KitsuneRal** [QMatrixClient/Quaternion#197]
This is an outlet from #48 to be addressed in the nearest time; specifically, to sort rooms alphabetically. This is a low-hanging fruit which, at the same time, improves UX quite a lot (as of now, UX with even 20-30 rooms is horrible).

**Comment by LarreaMikel** [comment]
I have also been thinking about this for uMatriks but with a different goal. Sort by newest message. Wouldn't it be better than the alphabetical sorting?

**Comment by alphapapa** [comment]
> Sort by newest message. Wouldn't it be better than the alphabetical sorting?

Sometimes, yes.  Sometimes, no.

**Comment by KitsuneRal** [comment]
Closed by #223 - thanks to @marcdeop!
