### ISSUE TITLE
Read marker no more aligned with Riot's

### ISSUE THREAD

**Issue by KitsuneRal** [QMatrixClient/Quaternion#210]
I suppose this is because of the implemented ReadMarker API that introduced an official cross-device read marker stored in account data. Depends on QMatrixClient/libqmatrixclient#123.

**Comment by krombel** [comment]
There are two steps: sending and reading.
The later one depends on QMatrixClient/libqmatrixclient#123.

But what's about sending?
For this the read marker with m.fully_read should be send.

**Comment by KitsuneRal** [comment]
Pre-spec, according to which Riot works, for the record: https://docs.google.com/document/d/1UWqdS-e1sdwkLDUY0wA4gZyIkRp-ekjsLZ8k6g_Zvso

**Comment by KitsuneRal** [comment]
Also, the spec issue: matrix-org/matrix-doc#910
