### ISSUE TITLE
Provide DEB for Debian / Ubuntu via PPA and RPM packages for Linux users

### ISSUE THREAD

**Issue by MurzNN** [QMatrixClient/Quaternion#211]
At now Quaternion releases have only windows packages and source code, so this is not so easy to try Quaternion for non-windows users.

Will be good to provide pre-compiled DEB packages for Debian / Ubuntu via manual download. 
Also will be good to see RPM packages for other popular distributives.

And best way for Linux users is provide Quaternion  package repository for auto-updating, via [PPA](https://help.launchpad.net/Packaging/PPA) or [openSUSE Build Service](https://build.opensuse.org/) 

This step will extend number of users and beta-testers of so perspective Quaternion Matrix client!

**Comment by KitsuneRal** [comment]
The Debian package has just been discussed in #quaternion - if it's all fine, Quaternion will soon land in Debian unstable (the package has been submitted and other packages of the same author recently got through to the repo). As for OBS, I know about [an attempt to package both the library and Quaternion](https://github.com/QMatrixClient/libqmatrixclient/issues/114) - hopefully @alexandergraul will make it happen (this might also mark the first reproducible usage of libqmatrixclient as a shared library).

**Comment by elvisangelaccio** [comment]
> At now Quaternion releases have only windows packages and source code, so this is not so easy to try Quaternion for non-windows users.

Not really, for Linux users there is also:

    flatpak install flathub com.github.quaternion

**Comment by KitsuneRal** [comment]
And we're still waiting for Snap advocates :)

**Comment by KitsuneRal** [comment]
@marcdeop, you might be interested in this.

**Comment by KitsuneRal** [comment]
For the record, Debian Buster and Sid packages can be found here: http://debian.uhoreg.ca/sid/quaternion/ and Stretch packages are here: http://debian.uhoreg.ca/backports/quaternion/ - hopefully they'll eventually land in respective official Debian repos.

**Comment by alexandergraul** [comment]
small update: I have started working on a RPM for openSUSE again. I still want to build it against a shared version of libqmatrixclient, which needs some adjustment with includes.

**Comment by KitsuneRal** [comment]
@alexandergraul, how's it going? Would be great to see libqmatrixclient 0.2 as a shared library.

**Comment by uhoreg** [comment]
Debian packages of 0.0.5 are now in Debian buster and sid.  I'll try to prepare packages for stretch-backports in the next few weeks.

**Comment by KitsuneRal** [comment]
Status report: according to [Repology](https://repology.org/metapackage/quaternion/information), OpenMandriva/Rosa (both RPM-based) have Quaternion packaged; it seems to only take a maintainer (or maintainers) to push the package to Fedora and OpenSUSE. @MurzNN, should we close it or keep it open until Quaternion lands in Fedora and/or OpenSUSE?

**Comment by alexandergraul** [comment]
There are unofficial packages for openSUSE in the openSUSE build service available, but they have not been submitted to the distribution yet. I could ask one of the maintainers on monday if he wants to do that.

**Comment by KitsuneRal** [comment]
Oh, that's a great news! Of course, please ask. Is that 0.0.9.3 (+lib 0.4.0) or 0.0.9.2 yet?

**Comment by alexandergraul** [comment]
It is 0.0.9.3 - if the version in the "devel" project is lower, I can push my "home" project version to it (we have multiple stages when it comes to packaging).

**Comment by KitsuneRal** [comment]
I wonder how much this is relevant - seems like somebody else built Quaternion (along with other Matrix packages) for OpenSUSE: https://build.opensuse.org/package/show/network:messaging:matrix/matrix-quaternion. He maintains `Qt >= 5.10` dependency for some reason though.

**Comment by alexandergraul** [comment]
The project maintainer of network:messaging:matrix is the one I will ask tomorrow how the state of that is. The Quaternion and libqmatrixclient packages were built by someone else though (if you click on "request 642587", you can see who did it), I can also ask him why he wants Qt >= 5.10 (this dependency makes it impossible to run on openSUSE Leap, our regular release distro).

**Comment by MurzNN** [comment]
> @MurzNN, should we close it or keep it open until Quaternion lands in Fedora and/or OpenSUSE?
I use Ubuntu, so will be good to have ready deb packages. At now I use flatpak version, but it eats too much storage and ram size, because use separate versions of all libs, instead of system. Flatpack is good for quick lookup (test new nightly version), but native Linux app will be much better for every day usage.

Here https://en.opensuse.org/openSUSE:Build_Service_Debian_builds is manual how to create debian packages via openSUSE, and here is working example: https://build.opensuse.org/package/show/openSUSE:Factory/snapper

Can you lookup it and add deb building rule, if this is not so hard? Thanks!

**Comment by alexandergraul** [comment]
@MurzNN unfortunately I don't know anything about building debian packages. OBS is great for that, but you still need to know what you are doing :laughing: 

@KitsuneRal 0.0.9.3 (without Qt >= 5.10) has been submitted and will hopefully be included in openSUSE Tumbleweed (our rolling release version) soon. The regular release version "Leap" will have a service pack next year, we have to wait until then.

**Comment by KitsuneRal** [comment]
@MurzNN, what's your Ubuntu version? Versions from this year already have Quaternion in `universe`.

**Comment by ptman** [comment]
Some helpful links:

https://packages.debian.org/search?keywords=quaternion

https://packages.ubuntu.com/search?keywords=quaternion

**Comment by MurzNN** [comment]
Yeah, thanks!
