### ISSUE TITLE
Chat edit history eats away messages that were retrieved and then edited

### ISSUE THREAD

**Issue by KitsuneRal** [QMatrixClient/Quaternion#231]
What seems to happen is that once the message is retrieved from history, it is deleted from there; but then the newly edited message doesn't get stored in history either. I'm not sure if the original should be deleted from history at all, but the newly edited message definitely should be saved.

**Comment by KitsuneRal** [comment]
@elvisangelaccio, FYI, the problem seems to be in `KChatEdit` so if you've taken this code somewhere or updated it elsewhere since then, you might want to sync it.

**Comment by elvisangelaccio** [comment]
@KitsuneRal Thanks for the info, though I have not pushed it anywhere yet, still living in a local branch of mine...

**Comment by KitsuneRal** [comment]
Then maybe at least update your local branch from the commit, there's also a memory leak plugged along the way :)
