### ISSUE TITLE
"Connect to server" box goes out of sync with "Matrix ID"

### ISSUE THREAD

**Issue by pafcu** [QMatrixClient/Quaternion#233]
When connecting, the connect to server box tries to autofill based on what is written in the "Matrix ID" box. However, it fails to actually stay synchronized if text is modified quickly.

![recording](https://user-images.githubusercontent.com/62835/34225373-86df541e-e5c6-11e7-8f11-fe7f4932880e.gif)

**Comment by KitsuneRal** [comment]
That looks to be one more breaking change in Qt 5.10 - with older Qt the "Connect to server" only refreshes on leaving the "Matrix ID" control. Thanks for reporting (and for the gif, it very much helps to understand what exactly is wrong with the behaviour).
