### ISSUE TITLE
Dynamic linking of Quaternion with libqmatrixclient

### ISSUE THREAD

**Issue by KitsuneRal** [QMatrixClient/Quaternion#239]
We're gradually coming to the state when libqmatrixclient has not only API but also ABI guarantees. Once this is done, it should be possible to build Quaternion separately from libqmatrixclient and link the two at runtime. This will please Linux distributions (they are rather unhappy when a library cannot be packaged separately); and who knows, maybe we'll start getting other clients and bindings in other languages thanks to that.

**Comment by awilfox** [comment]
> The library is still built statically into Quaternion; if you'd like to take part in uncoupling the two, you're welcome in #239.

How can I help?  I'm the project lead of [one of those aforementioned Linux distributions](https://adelielinux.org) that would love to have the library decoupled; I'm a moderately skilled Qt programmer; and I am also a regular user of Quaternion.

**Comment by awilfox** [comment]
Okay, so packaging Quaternion for Adélie instead of just running it from the build directory:

* It defaults to building a .so instead of an .a, at least here (GCC 6.4.0, binutils 2.29, ppc64 and x86_64)
* The .so file is not installed to /usr/lib, so the software fails to run due to a missing library:

```
awilcox on reynard [pts/6 Sat 30 16:25] ~: quaternion
Error loading shared library libqmatrixclient.so.0: No such file or directory (needed by /usr/bin/quaternion)
Error relocating /usr/bin/quaternion: _ZN13QMatrixClient4RoomD2Ev: symbol not found
```

After applying a [small patch](https://code.foxkit.us/adelie/packages/blob/master/user/quaternion/install-library.patch) to install the library, it seems to work fine.  If this patch would be helpful I would be happy to put it in a pull request.

**Comment by KitsuneRal** [comment]
Thanks a lot! As far as I understand it, there are two parts here:
1. Make sure the library gets installed to the right location so that it can be packaged. Your patch does that - please submit it to the `QMatrixClient/libqmatrixclient` repo.
2. Make sure that versioning of the library is correct (not only .so but also .so.* files are generated). As far as I see above, that seems to work as well.

**Comment by KitsuneRal** [comment]
Oh, sorry, there's one more thing - but that's really above compiling against the dynamically linked library. The library headers should be installed to the standard place (`/usr/include` or whatever the distribution uses). So while you're at it, I'd appreciate if you add one more line to your patch that takes all `.h` files from `lib/` and installs them.

**Comment by KitsuneRal** [comment]
As @alexandergraul found it the harder way, `.h` files should be taken from `lib/` and its subdirectories.

**Comment by KitsuneRal** [comment]
The "install" part has been done; this now depends on QMatrixClient/libqmatrixclient#195. @awilfox, you're welcome to help there.

**Comment by KitsuneRal** [comment]
@alexandergraul, @awilfox, is there anything I should additionally do or does Quaternion already build (and install and run) with a separately installed libQMatrixClient?

**Comment by arunisaac** [comment]
I am packaging quaternion for Guix. I was able to dynamically link quaternion to libqmatrixclient by removing the `add_subdirectory(lib)` line from `CMakeLists.txt` and fixing all #include header lines to not refer to `lib`.

**Comment by KitsuneRal** [comment]
Thanks for the effort, @arunisaac!
Whichever `#include` lines refer to `lib` should be patched - a PR for that is very welcome.
As for `add_subdirectory()`, a CMake option should be introduced that would switch between that and `find_package(libqmatrixclient)` (generally, one can't rely on libqmatrixclient being installed to standard paths). For that, a PR is also (of course) welcome :)

**Comment by arunisaac** [comment]
Can we just abandon static linking and move to dynamic linking? That
way, we wouldn't have to introduce a new CMake option. If I understand
correctly, CMake is capable of finding libqmatrixclient wherever it is
installed.

I don't know much about CMake. And, in case we do decide to support both
static and dynamic linking, I don't feel confident enough to send a
PR. If we are supporting only dynamic linking, I'd be happy to send a PR.

**Comment by arunisaac** [comment]
Meanwhile, I have packaged libqmatrixclient and quaternion for Guix.

https://git.savannah.gnu.org/cgit/guix.git/commit/?id=9a3da9859be2c7b89c344c7aea5b682093932530
https://git.savannah.gnu.org/cgit/guix.git/commit/?id=e81c952a4da21c7772f8104f4fcc44af3f403daf

**Comment by KitsuneRal** [comment]
I'm glad that the code is basically in condition for dynamic linking, barring `#include`'s.
It's not so much about static vs. dynamic linking as it is about having two build sequences instead of one. Given that in 99% of cases people building Quaternion afresh don't have libQMatrixClient around, I'd rather they do the cmake dance only once without building the library separately.
For now, just having those `#include` lines stripped of `lib` and using angle brackets is enough for a PR :) I'll tackle the CMake stuff on my end.

**Comment by arunisaac** [comment]
> For now, just having those `#include` lines stripped of `lib` and
> using angle brackets is enough for a PR :) I'll tackle the CMake stuff
> on my end.

Sure, will send you a PR soon! :-)

**Comment by awilfox** [comment]
Sorry, have been away for some time setting up new hardware.  Will be testing this again soon.  Progress is looking good on Quaternion!
