### ISSUE TITLE
Optionally hide join/leave and/or redacted events from the timeline

### ISSUE THREAD

**Issue by KitsuneRal** [QMatrixClient/Quaternion#248]
This is a part of bigger #219 that is easy to implement and greatly improves experience with IRC netsplits. There should be a global setting, overridable per-room.

**Comment by KitsuneRal** [comment]
In the light of IRC spam this becomes quite needed.

**Comment by KitsuneRal** [comment]
Closed by f3b13f6dbdc8cdcb33a43cba76e23c9a4da4bb04

**Comment by peterhoeg** [comment]
So how does one hide the state changes @KitsuneRal? I haven't found a way to do that in Quaternion.

**Comment by KitsuneRal** [comment]
It's in the menu: View ->Display in Timeline -> ... Of all state changes, only joins/leaves can be switched on/off for now.

**Comment by peterhoeg** [comment]
Should have found that, sorry. Thanks for the help.
