### ISSUE TITLE
empty chat log ubuntu 17.10

### ISSUE THREAD

**Issue by TurBoss** [QMatrixClient/Quaternion#264]
Hello:

    Master branch compiled from sources

![imagen](https://user-images.githubusercontent.com/184088/34913628-d7a6f204-f902-11e7-8b01-39d4eae0bcc3.png)

this is what I can see

Thanks

**Comment by TurBoss** [comment]
sorry my fault some deps were not installed
```
    sudo apt -y install qml-module-qtquick-controls install qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel
```
Thanks

**Comment by KitsuneRal** [comment]
As far as I know, if these only Qt Quick Controls are needed. Qt Labs parts are not used in Quaternion as of now.

**Comment by TurBoss** [comment]
I had console log complaining about Qt Labs

```
module "Qt.labs.settings" is not installed
```

**Comment by KitsuneRal** [comment]
Just as a sidenote - that's puzzling, I don't see any mention of Qt.labs modules in the source code. The Settings QML object is (should be, at least) provided by Quaternion itself not taken from Qt Labs.

**Comment by TurBoss** [comment]
If I uninstall "qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel"

I get this on the console

```
$ quaternion 
qrc:///qml/chat.qml:432:29: Type FileDialog unavailable
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:47:1: module "Qt.labs.folderlistmodel" is not installed 
     import Qt.labs.folderlistmodel 2.1 
     ^
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:48:1: module "Qt.labs.settings" is not installed 
     import Qt.labs.settings 1.0 
     ^
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:47:1: module "Qt.labs.folderlistmodel" is not installed 
     import Qt.labs.folderlistmodel 2.1 
     ^
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:48:1: module "Qt.labs.settings" is not installed 
     import Qt.labs.settings 1.0 
     ^

```

**Comment by KitsuneRal** [comment]
Oh, I see - so at least on Ubuntu the QML file dialog apparently uses pieces from Qt.labs. I'll see what's better, to avoid using the QML file dialog or document these deps.

**Comment by TurBoss** [comment]
I leave that in your hands :D

**Comment by KitsuneRal** [comment]
Thanks for following up on that, anyway. (For the record: from the next commit Quaternion will go on without QML file dialog and extra Qt.labs deps caused by it).
