### ISSUE TITLE
broken inline image display

### ISSUE THREAD

**Issue by tidux** [QMatrixClient/Quaternion#274]
Currently built from commit 551f1e74be4d8d9422c740d55ebd49e8c481ae50.

![screenshot_20180117_103809](https://user-images.githubusercontent.com/1330562/35060259-bf0e871c-fb72-11e7-86d3-913308076df9.png)

Same behavior exists with and without condense_chat=true in quaternion.conf.

**Comment by KitsuneRal** [comment]
Should be fixed by 551f1e74be4d8d9422c740d55ebd49e8c481ae50

**Comment by tidux** [comment]
Some bridged IRC rooms have missing text after the change and this message appears over and over on stderr:

`QPainter::begin: Paint device returned engine == 0, type: 3`
