### ISSUE TITLE
Add OARS to appdata

### ISSUE THREAD

**Issue by nedrichards** [QMatrixClient/Quaternion#314]
It'd be great to see the appdata get an [OARS rating](https://hughsie.github.io/oars/), which would allow Linux software stores to categorise the app appropriately. This is one of the emerging flathub requirements and is pretty easy to do (answer a few questions and copy and paste some XML).

**Comment by KitsuneRal** [comment]
@elvisangelaccio, would you mind if I use CC-BY-4.0 for metadata instead of CC Zero?

**Comment by elvisangelaccio** [comment]
@KitsuneRal go for it!

(Sorry, I thought I had replied you in the matrix channel, but I didn't)
