### ISSUE TITLE
Can't load channels in 0.0.9

### ISSUE THREAD

**Issue by E5ten** [QMatrixClient/Quaternion#355]
### Description

When I start 0.0.9, no messages of any kind load when I click any channels

### Steps to reproduce

Compile 0.0.9
Start it
Try to load a channel

Describe how what happens differs from what you expected.

I expect to see messages, instead none are loaded.

### Version information
- **Quaternion version**:
0.0.9
- **Qt version**: 
5.10.1
- **Install method**: 
Compiled from the AUR and also manually from the github repo, same results
- **Platform**: 
Arch Linux, LTS kernel.

**Comment by KitsuneRal** [comment]
Previously that message has been a red herring. The good news at least is that your QML appears to be working (otherwise the logs would be pretty quiet). By chance, do you have a dark UI scheme?

**Comment by E5ten** [comment]
I do. I guess that means I should test with a light theme?

**Comment by KitsuneRal** [comment]
Yes, please. I thought I fixed all the issues concerned with it but you never know where a bug creeps in.

**Comment by E5ten** [comment]
Yep, with a light theme it works.

**Comment by KitsuneRal** [comment]
Given that Quaternion runs on a dark theme on my machine (just checked), let's see if there's something about QML on your machine. Do any of Qt/QML examples work fine (they should be a part of your `qt5-declarative` package)?

**Comment by E5ten** [comment]
How do I run those?

**Comment by E5ten** [comment]
If you mean like the C++ and QML here both worked https://wiki.archlinux.org/index.php/Qt#Bindings

**Comment by KitsuneRal** [comment]
`hello.qml` from that should be fine too, yes. Ok, so far I'm out of ideas why it sets the foreground colour improperly. By the way - can you try opening some room with images and check whether at least images show?

**Comment by E5ten** [comment]
I'm not in any rooms with images as far as I know, do you have a test one I could join?

**Comment by KitsuneRal** [comment]
`#test:matrix.org` is a great option for that - there's just been an image posted there, by the way.

**Comment by E5ten** [comment]
I see nothing there right now but I don't know if the image is still close to the front.

**Comment by KitsuneRal** [comment]
Well, you can blindly scroll up but in fact the image is just 10 lines above the bottom (now that you've joined). You don't see the date section (the lighter band across the timeline) either, do you?

**Comment by E5ten** [comment]
I do not, and blindly scrolling up a bunch revealed nothing sadly :(

**Comment by KitsuneRal** [comment]
Then QML doesn't work right. Please do the following: enter any room, (blindly) scroll up and down, then post the terminal output here (if any).

**Comment by E5ten** [comment]
qrc:///qml/TimelineItem.qml:156:13: QML TextEdit: Protocol "mxc" is unknown

**Comment by E5ten** [comment]
pretty sure that's the relevant line at least.

**Comment by KitsuneRal** [comment]
Yes, moreover, this is a valid URL and usually, if there are no warnings next to this line, this means that the ImageProvider properly fetches the image.
Actually, I've just realised that the unknown protocol warning is a separate issue: it relates to a rich text control apparently trying to show an image in `<img>`, known not to work.
As for your problem - do you see lines like "Saving viewport: x thru y" in the terminal output?

**Comment by KitsuneRal** [comment]
(specifically, those lines should show up when you scroll the timeline)

**Comment by E5ten** [comment]
I do not.

**Comment by KitsuneRal** [comment]
Ok, then the possible conclusion is: your QML engine seems to be up and running, showing events and all, but the viewport for the timeline is somehow incorrect: either its size is zero or the viewport is grossly misplaced.
I think I will add some more debug information in the code to figure what's going on. I'll let you know when I have some commits for you.

**Comment by E5ten** [comment]
Thanks.

**Comment by KitsuneRal** [comment]
@E5ten, please try to build and run the above commit; I'm interested in log lines with `onShownChanged`.

**Comment by KitsuneRal** [comment]
As also mentioned in #356, please try to build Quaternion from master now, passing `-DUSE_QQUICKWIDGET` to CMake. This may help with QML visibility problems but might or might affect Quaternion stability. Try to use it heavily (in particular open rooms with images, such as `#test:matrix.org`).

**Comment by Criminalllz** [comment]
@E5ten Are you using qt5ct?

For me this only happens with breeze, on all color schemes.

Also, setting -DUSE_QQUICKWIGET=ON fixes the issue for me.

**Comment by E5ten** [comment]
I was using breeze and qt5ct, but I'm not on same computer anymore and I don't know if it's fixed in master or if something else changed but I don't get the issue anymore.

**Comment by KitsuneRal** [comment]
@Criminalllz, is it stable with `-DUSE_QQUICKWIDGET=ON`? I already got a couple reports that it's pretty crashy.

**Comment by Criminalllz** [comment]
@KitsuneRal Nope, just crashed when clicking an image

**Comment by KitsuneRal** [comment]
Thanks for testing. I'll try to find other workarounds then.

**Comment by KitsuneRal** [comment]
Qt 5.12 brings some fixes for QQuickWidget - please check if it's more stable now (it is on my machine).

**Comment by KitsuneRal** [comment]
For older Qt versions, [a recommendation in this Qt bug report](https://bugreports.qt.io/browse/QTBUG-64697) might be relevant (even though it refers to Windows 10): try to pass `-DUSE_QQUICKWIDGET=ON` to CMake and set `QT_DISABLE_SHADER_DISK_CACHE=1` as environment variable before running Quaternion.

**Comment by KitsuneRal** [comment]
Closing this for now; feel free to reopen if with Qt 5.12 and `-DUSE_QQUICKWIDGET=ON` Quaternion still crashes. Meanwhile, `QQuickWidget` is likely to become the default used engine with Qt 5.12, and it's a `wontfix` for Qt 5.11 and earlier, unfortunately.
