### ISSUE TITLE
Maybe don't use a different text color for highlighted events

### ISSUE THREAD

**Issue by KitsuneRal** [QMatrixClient/Quaternion#370]
The highlight color is (by default) alarming enough to make the text in that color less readable - especially if the text is long (see https://matrix.to/#/!YkZelGRiqijtzXZODa:matrix.org/$15296800015801znPgI:t2l.io and the message leading to it). So either that should be a frame around the event, or background in that color instead (in case of background it of course should be a tint over the background color).

**Comment by rushsteve1** [comment]
Ideally this should be configurable.
But for now what do you think of bolding instead of highlighting. And then perhaps slightly coloring (all?) nicknames to distinguish them.

**Comment by KitsuneRal** [comment]
Nicknames tinting is a separate thing that would be great to do. As for bold text - to be frank, I'm not a big fan of that either.
Configurability - well... People have strong opinions on whether "everything should be configurable" :) Being a former GNOME person, I prefer keeping options under close control.
I tend to choosing the frame or some kind of a marker instead. As the least change from the current, colour-highlighting the specific word/nick that caused the _protocol_ highlighting of the event should be much less intrusive than highlighting the entire text.

**Comment by KitsuneRal** [comment]
As of the commit above, the highlighting mode _is_ configurable between background/text but not exposed in UI. Using a frame for highlighting didn't look good but if anybody wants I can make it available too (it's really easy now).
