### ISSUE TITLE
suggestion: automatically enable Xchat layout if condense_chat=1 

### ISSUE THREAD

**Issue by tidux** [QMatrixClient/Quaternion#373]
User names are not being kept on the same lines as text anymore.  This may be a platform specific issue as I see it on Linux but not Windows.

**Comment by tidux** [comment]
Updating from 0.0.9 to 0.0.9.2 apparently kept condense_chat but did not enable the IRC style layout.  Issue title edited to reflect.

**Comment by KitsuneRal** [comment]
I'm afraid I cannot agree with this - I just discovered that I myself use the condensed chat together with the new-default layout. And switching the layout is as easy as picking a menu item in 0.0.9.2. Feel free to reopen if you believe I'm missing something.
