### ISSUE TITLE
Add functionality for collapsing room description

### ISSUE THREAD

**Issue by akrusemark** [QMatrixClient/Quaternion#384]
The descriptions for some rooms are very long, and they can take a lot of space from the chat area when the Quaternion window is small. It'd be great to have a button in the room description area to let the user collapse it down to just the room icon and name, and then expand it again if needed.

- **Quaternion version**: 0.0.9.2
- **Qt version**: 5.10.1
- **Install method**: Official Debian Repository
- **Platform**: Debian testing/unstable

**Comment by KitsuneRal** [comment]
I'm pretty sure there's already been an issue about that but can't find it quickly.

**Comment by KitsuneRal** [comment]
Oh, of course it's here: #338. Feel free to upvote so that it lands in 0.1.
