### ISSUE TITLE
Dark theme and flatpak

### ISSUE THREAD

**Issue by qazip** [QMatrixClient/Quaternion#389]
### Description

I've installed quaternion via flatpak and also the Arc-Dark theme (via flatpak), which is the theme I am using on my system. My window manager is i3wm.

I'd like to use quaternion's dark theme, but it doesn't seem to work. I thought that by having the theme installed in flatpak, that quaternion would use it automatically.

So, my question is:

- How does one use a dark theme with quaternion via flatpak?

### Version information

- **Quaternion version**: It's the flatpak version. By the way, I can't find an "about" section in quaternion, to find the version..
- **Install method**: Flatpak
- **Platform**: Ubuntu 16.04 with i3wm

**Comment by KitsuneRal** [comment]
The Flatpak version (0.0.9.2, I suppose) has not gained the About window yet, sorry (upcoming 0.0.9.3 has it). And unfortunately I can't help much with your question - theme support is a well known problem of all "let's pack the libraries along with the application" solutions, Flatpak inclusive. Upgrading to bionic and using a proper Quaternion package from cosmic on top of it might be a better option...

**Comment by KitsuneRal** [comment]
Closing this - you may better try your chances in some forum/website on Flatpak since your problem is not really specific to Quaternion.
