### ISSUE TITLE
Crash on startup after room loading.

### ISSUE THREAD

**Issue by zsinskri** [QMatrixClient/Quaternion#395]
### Description

When starting Quaternion I can log in and briefly (maybe a quarter second?) see 
- my room list,
- the list of room participants, 
- the `Yesterday` marker 
- but not the yet any messages, 

then the application closes unexpectedly.

### Steps to reproduce

- `flatpak install flathub com.github.quaternion`
- `flatpak run com.github.quaternion` (or launch from menu)
- login
- wait briefly while rooms load
- Quaternion quits.

I expected Quaternion not to quit but to let me read my messages.

#### reproducibility

I tried reinstalling Quaternion and its flatpak dependencies (`org.kde.Platform//5.9`) multiple times. I also tried removing `~/.var/app/com.github.quaternion` to wipe any settings. I tried to login with `@<username>:matrix.org` and with `<username>`.
I could reproduce this issue every time.
I did not try it on any other system or matrix account than mine.

### log
```sh
$ flatpak run com.github.quaternion --debug
Debug:  true
Using QQuickView wrapper instead of QQuickWidget
qml: QML view loaded
qml: Base colours: #232627 on #fcfcfc
org.kde.knotifications: env says KDE is running but SNI unavailable -- check KDE_FULL_SESSION and XDG_CURRENT_DESKTOP
--- Show time!
qml: Chat: getPreviousContent disabled
Connected to room "!HBA<redacted>rROj:matrix.org" as "@<redacted>:matrix.org"
qml: Chat: getPreviousContent enabled
Sorting 0 user(s) in "" took 11 µs
0 user(s) in the room
2 ms to  select room 
QImage::scaled: Image is a null image
QImage::scaled: Image is a null image
QImage::scaled: Image is a null image
Read marker is on-screen, at (94|"$153<redacted>qTMC:matrix.org")
Read marker is off-screen
Bottommost shown message index was 94
ImageProvider::requestImage: "mxc://matrix.org/<redacted>"
Read marker is on-screen, at (94|"$153<redacted>qTMC:matrix.org")
libqmatrixclient.jobs: "GetContentThumbnailJob" stopped without ready network reply
QImage::scaled: Image is a null image
QImage::scaled: Image is a null image
ASSERT: "userId.startsWith('@') && userId.contains(':')" in file /run/build/quaternion/lib/lib/connection.cpp, line 637
```
(The output also contained `QPainter::begin: Paint device returned engine == 0, type: 3` about 32 times, which was called a red-herring in an other issue…)

### guessing

I think I might have once written a message starting with an `@` not followed by username:homeserver.tld, though I cannot find that message now. Maybe that triggered some `@mention` parser that asserted a valid Matrix ID?
```sh
ASSERT: "userId.startsWith('@') && userId.contains(':')" in file /run/build/quaternion/lib/lib/connection.cpp, line 637
```
But might be anything else as well…

### Version information

- **Quaternion version**: `quaternion 0.0.9.2`
- **Qt version**: `5.9` (I guess that is the Qt version in the flatpak `org.kde.Platform/x86_64/5.9`?) 
- **Install method**: flatpak (flathub)
- **Platform**: GNU/Linux: Fedora 28 (KDE spin)

**Comment by zsinskri** [comment]
I just created a fresh account and could not reproduce this issue with it.
I also tried sending a message "`@Test`", that did not trigger the crash either. (I guess a `@mention` parser would not have been in `connection.cpp`, anyways)

Switching back to my own account immediately crashed Quaternion with the same assertion message.

If there is something else I could try to help with this issue, please tell me.

**Comment by KitsuneRal** [comment]
Thank you for the report. This assertion fails only when trying to resolve a user by a malformed user id, encountered in some event. It's a bit more likely though that libQMatrixClient has a bug somewhere. Can you please find a core dump file and get a backtrace for me?

**Comment by KitsuneRal** [comment]
Also, thanks for the guess, but such malformed id should be in the metadata, not in the content.

**Comment by zsinskri** [comment]
Backtrace: https://ptpb.pw/zCdo

I now compiled Quaternion from source as I could not find out how to get a backtrace from flatpak. 
I tried both master (commit: f3b13f6) and the tag v0.0.9.2, the backtrace is from the later. Both did crash.

I have almost no experience with C++ and its debugging tools, so please tell me if you need something else. Should I install the debuginfos for all of the dependencies?

**Comment by KitsuneRal** [comment]
The backtrace is interesting. May I ask you to open `/devtools` in Riot and send me the contents of your `m.direct` account data event? `@kitsune:matrix.org` in Matrix is fine, or you can use good ol' email and send the contents to `Kitsune-Ral@users.sf.net`. That's rather to confirm my guess that what I found causes your problem.

**Comment by zsinskri** [comment]
OK, thank you!

I did try to clean my m.direct up, and then log into all clients I can remember using (Tensor for Android (where the login failed), Riot for Android/Web, nheko, Quaternion), and none of those regenerated those invalid entries.

I did forget to check if `master` is fixed, I'll try adding one of the invalid entries back…

**Comment by zsinskri** [comment]
I did add a m.direct entry, confirmed that 0.0.9.2 crashs with the same error message.
After building with libqmatrixclient commit 4442a820c8617fbb5352c44456105c0571143f58 it does not crash but instead shows this (expected) warning:
```
libqmatrixclient.main: Malformed userId: "Name@matrix.org"
libqmatrixclient.main: Couldn't get a user object for "Name@matrix.org"
```
I'll continue to try to find how those invalid matrix IDs got there. (Keeping in mind that it might already have long been fixed).

Thank you very much for resolving this issue so quickly!

**Comment by KitsuneRal** [comment]
You're welcome :) I'll keep this option open for now, as Quaternion didn't get a commit that would grab the fixed library rather than the old one. Will close it later today.
