### ISSUE TITLE
Option to hide menu bar icon

### ISSUE THREAD

**Issue by aaronraimist** [QMatrixClient/Quaternion#460]
### Description

I'd love to get an option to be able to hide the macOS menu bar icon. Usually this would either been an option in the preferences window, when right clicking/option clicking the menu bar icon, or maybe in the view menu.

### Version information

- **Quaternion version**: v0.0.9.3
- **Install method**: Homebrew
- **Platform**: macOS 10.13.6

![screen shot 2018-12-23 at 7 54 30 pm](https://user-images.githubusercontent.com/5855073/50389223-4e2b7f00-06ed-11e9-846b-7ed8f8e72de6.png)

**Comment by KitsuneRal** [comment]
See #190.
