### ISSUE TITLE
broken Info.plist on macOS

### ISSUE THREAD

**Issue by core-code** [QMatrixClient/Quaternion#462]
most of the entries in your Info.plist file are empty, which hinders macOS native integration.

each app needs a bundle identifier (CFBundleIdentifier), not having it will break cache and preferences

each app needs version information (CFBundleVersion & CFShortVersionString), so you can see its version in the Finder

the CFBundleLongVersionString and CFBundleGetInfoString entries have been deprecated for > 10 years and can be removed

**Comment by KitsuneRal** [comment]
@aaronraimist, can you take a look at this?

**Comment by aaronraimist** [comment]
Yeah I was already planning on setting CFBundleShortVersionString but I don't know enough about cmake to be able to do that. Meant to ask a few questions in the matrix room a few days ago, will do so now.

**Comment by core-code** [comment]
thanks!

**Comment by core-code** [comment]
i can confirm this is fixed in 0.0.9.4
