### ISSUE TITLE
can't close About

### ISSUE THREAD

**Issue by Lonsfor** [QMatrixClient/Quaternion#472]
### Description

"about" doesn't have an icon to close it

![2019-01-16-23-01-28](https://user-images.githubusercontent.com/15758649/51290755-8b3d1580-19fc-11e9-8a3f-2df901db61c8.png)

### Steps to reproduce

-open "about"
-try to close it
-can't

### Version information

- **Quaternion version**: master
- **Qt version**: 5.11.2 
- **Install method**: archive downloaded
- **Platform**: linux

**Comment by KitsuneRal** [comment]
What's your window manager?
As a workaround, your usual close-window keyboard shortcut should do the trick.

**Comment by Lonsfor** [comment]
Macro (the window manager for Mate)
