### ISSUE TITLE
Disable smooth scroll

### ISSUE THREAD

**Issue by qazip** [QMatrixClient/Quaternion#483]
Scrolling on quaternion is weird. It feels way too "smoothy". It would be awesome if there was an option to disable smooth scroll.

Quaternion version: 
```
v0.0.9.3
Built from Git, commit SHA:
3bad73860bb39714c23694b8c1d280583a003b8b
```

**Comment by sdicke** [comment]
I have the same feeling.

**Comment by sdicke** [comment]
It should be considered if the smoothness should be adjustable.

**Comment by KitsuneRal** [comment]
@qazip , @sdicke - can you please try the CI version from https://bintray.com/qmatrixclient/ci/Quaternion and tell if there's difference? The scrolling kinetics have been changed since 0.0.9.3.

**Comment by KitsuneRal** [comment]
I'm going to close this one for now as I assume that scrolling is no more "too smooth" (aka stubborn). Feel free to reopen if the experience is still not good still.
