### ISSUE TITLE
Name changes show the old name twice

### ISSUE THREAD

**Issue by medusacle** [QMatrixClient/Quaternion#496]
Basically, name-change events are shown as `X changed their name to X`. For example the same event shows

- Like this in Quaternion:

![event_quaternion](https://user-images.githubusercontent.com/43048142/52851961-a98b5380-3117-11e9-8798-0a7b6b65efab.png)

- Like this in riot.im:
![event_riot](https://user-images.githubusercontent.com/43048142/52851810-5a452300-3117-11e9-947a-4915e79d1a5b.png)

This is with current master, commit ff787a12f73695cfc625092b3922b30c475697aa.

**Comment by KitsuneRal** [comment]
See #317.

**Comment by medusacle** [comment]
thanks, sorry, hadn't noticed an issue for this already exists (did search for it)
