### ISSUE TITLE
'Send message (unencrypted)' is too harsh

### ISSUE THREAD

**Issue by KitsuneRal** [QMatrixClient/Quaternion#500]
Not that it was completely unencrypted, just not E2E encrypted.

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/3628

You probably want to solve it in a similar way to Riot (although who knows how they are going to solve it)

**Comment by KitsuneRal** [comment]
Thanks, and interesting read. Probably I'd just drop "(unencypted)" for now.
