### ISSUE TITLE
Group description able to take up half of the screen.

### ISSUE THREAD

**Issue by ilya-fedin** [QMatrixClient/Quaternion#504]
### Description

![default](https://user-images.githubusercontent.com/17829319/53203546-e3da8080-3642-11e9-8cc6-5ca77074e599.png)

### Steps to reproduce

Open group with very long description

### Version information

- **Quaternion version**: 0.0.9.3
- **Install method**: Flatpak
- **Platform**: Linux (NixOS)

**Comment by KitsuneRal** [comment]
See #338.
