### ISSUE TITLE
Update Mac info.plist to show RC in version

### ISSUE THREAD

**Issue by aaronraimist** [QMatrixClient/Quaternion#578]
otherwise the crash log says 0.0.9.4 for 0.0.9.4-rc2 like https://github.com/QMatrixClient/Quaternion/issues/566#issuecomment-482379573

- [ ] and also name the .dmg like the Windows builds

**Comment by KitsuneRal** [comment]
The main part is due to `CMakeLists.txt` reporting a version without RC (which was incorrect). Now that we're at the release this is no more relevant. The renaming will be done.
