### ISSUE TITLE
Trying to build latest 0.0.9.4 and I hit this error

### ISSUE THREAD

**Issue by doronbehar** [QMatrixClient/Quaternion#584]
### Description

```
CMake Error at CMakeLists.txt:82 (find_package):
  Could not find a configuration file for package "QMatrixClient" that is
  compatible with requested version "0.5.1".

  The following configuration files were considered but not accepted:

    /var/packages/archlinux/sources/quaternion/src/Quaternion-0.0.9.4/lib/cmake/QMatrixClientConfig.cmake, version: unknown

-- Configuring incomplete, errors occurred!
See also "/var/packages/archlinux/sources/quaternion/src/Quaternion-0.0.9.4/build/CMakeFiles/CMakeOutput.log".
```

### Steps to reproduce

- Download https://github.com/QMatrixClient/Quaternion/archive/v0.0.9.3.tar.gz
- Download https://github.com/QMatrixClient/libqmatrixclient/archive/v0.4.0.tar.gz
- Untar both
- Untar libqmatrixclient archive into subdir `lib` of Quaternion.
- Run the following in Quaternion's directory:
```
  cmake -H. -Bbuild \
    -DCMAKE_CXX_FLAGS:STRING="${CXXFLAGS}" \
    -DCMAKE_EXE_LINKER_FLAGS:STRING="${LDFLAGS}" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS=ON \
    -DUSE_INTREE_LIBQMC=OFF

  cmake --build build
```

**Comment by KitsuneRal** [comment]
Well, as you can see from the error message, you should use libQMatrixClient 0.5.1 or higher (the latest version is always on the top here, by the way: https://github.com/QMatrixClient/libqmatrixclient/releases). I'm not sure you actually downloaded Quaternion 0.0.9.3, as you described in the steps to reproduce (that one actually needs lib 0.4.x).

**Comment by doronbehar** [comment]
> I'm not sure you actually downloaded Quaternion 0.0.9.3, as you described in the steps to reproduce (that one actually needs lib 0.4.x).

My bad, I've mistakenly copied wrong URLs, to be precise, I've tried to update the Arch Linux `PKGBUILD` and these are the correct URLs:

- https://github.com/QMatrixClient/Quaternion/archive/0.0.9.4.tar.gz
- https://github.com/QMatrixClient/libqmatrixclient/archive/0.5.1.2.tar.gz

I'm still having this issue. Is there a chance you can check please if the library's archive and the git submodule act the same?

**Comment by KitsuneRal** [comment]
Ok, if it's really about the current versions of both, you should double-check if it's correct using `-DUSE_INTREE_LIBQMC=OFF` because this disables looking for the library sources in `lib/`.

**Comment by doronbehar** [comment]
Oh, thanks. That worked, I thought that this flag referred to this package: https://qmc2.batcom-it.net
