### ISSUE TITLE
Create a new room marked as direct chat and invite user, when using /query.

### ISSUE THREAD

**Issue by maralorn** [QMatrixClient/Quaternion#90]

**Comment by KitsuneRal** [comment]
Depends on QMatrixClient/libqmatrixclient#34.

**Comment by KitsuneRal** [comment]
Also, similar to (but different in terms of UI) to #30.

**Comment by KitsuneRal** [comment]
Depends on QMatrixClient/libqmatrixclient#163, because we don't want to make a new direct chat on each `/query`, we have to reuse an existing one.
