### ISSUE TITLE
A lot of people typing at the same time will resize the window

### ISSUE THREAD

**Issue by maralorn** [QMatrixClient/Quaternion#93]
I think this is more an academic bug.
If a lot of people type at the same time, the list over the input bar gets so long, that the main window grows in width, at least with my WM in floating mode.

**Comment by KitsuneRal** [comment]
Not so much academic, in fact - it's surprisingly easy (and especially annoying) to get to that on screens with lower resolutions, combined with disambiguated display names (of which there are more than 2 with some users). Moving this to 0.0.5 hence.

**Comment by KitsuneRal** [comment]
Still observed as of the latest master

**Comment by KitsuneRal** [comment]
Not observed, as of Qt 5.10 on Windows 7. Feel free to reopen if reproduced on some other platform (please specify it when reopening).
